export {
  buildProjectGroups,
  deriveLogicalProjectKey,
  deriveLogicalProjectKeyFromRef,
  deriveLogicalProjectKeyFromSettings,
  derivePhysicalProjectKey,
  derivePhysicalProjectKeyFromPath,
  deriveProjectGroupLabel,
  deriveProjectGroupingOverrideKey,
  getProjectOrderKey,
  resolveProjectGroupingMode,
  selectProjectGroupingSettings,
  type ProjectGroupingMode,
  type ProjectGroupingSettings,
  type ProjectGroup,
  type ProjectGroupMember,
} from "@embedino/client-runtime/state/project-grouping";
